# Generated by Django 5.2.14 on 2026-05-13 08:56

import django.db.models.deletion
import django_ckeditor_5.fields
import parler.fields
import parler.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/about', verbose_name='Rasm 1')),
                ('image2', models.ImageField(upload_to='images/about', verbose_name='Rasm 2')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
            ],
            options={
                'verbose_name': 'Kompaniya haqida',
                'verbose_name_plural': 'Kompaniya haqida',
                'ordering': ['-created_at'],
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(max_length=300, verbose_name='Matn')),
                ('students', models.IntegerField(default=0, verbose_name='Talabalar soni')),
                ('direction', models.IntegerField(default=0, verbose_name="Yo'nalishlar soni")),
                ('specialist', models.IntegerField(default=0, verbose_name='Mutaxassislar soni')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
            ],
            options={
                'verbose_name': 'Biz haqimizda',
                'verbose_name_plural': 'Biz haqimizda',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Aboutusimages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='images/aboutusimages', verbose_name='Rasm')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
            ],
            options={
                'verbose_name': 'Biz haqimizda rasm',
                'verbose_name_plural': 'Biz haqimizda rasmlar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ConnectionForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Ism')),
                ('phone', models.CharField(max_length=9, verbose_name='Telefon')),
                ('comfort_time', models.CharField(choices=[('8:00 - 10:00', '8:00 - 10:00'), ('10:00 - 12:00', '10:00 - 12:00'), ('14:00 - 16:00', '14:00 - 16:00')], default='8:00 - 10:00', max_length=50, verbose_name='Qulay vaqt')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
            ],
            options={
                'verbose_name': "Bog'lanish formasi",
                'verbose_name_plural': "Bog'lanish formalari",
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HistoryTechnopark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
            ],
            options={
                'verbose_name': 'Texnopark tarixi',
                'verbose_name_plural': 'Texnopark tarixi',
                'ordering': ['-created_at'],
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='MainServices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/services', verbose_name='Rasm')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
            ],
            options={
                'verbose_name': 'Asosiy xizmat',
                'verbose_name_plural': 'Asosiy xizmatlar',
                'ordering': ['-created_at'],
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='images/news', verbose_name='Rasm')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
            ],
            options={
                'verbose_name': 'Yangilik',
                'verbose_name_plural': 'Yangiliklar',
                'ordering': ['-created_at'],
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='QuestionForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Ism')),
                ('phone', models.CharField(max_length=9, verbose_name='Telefon')),
                ('company_name', models.CharField(max_length=100, verbose_name='Kompaniya nomi')),
                ('body_small', models.TextField(max_length=200, verbose_name='Savol matni')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('edit_allow', models.BooleanField(default=True, verbose_name='Tahrirlashga ruxsat')),
            ],
            options={
                'verbose_name': 'Savol formasi',
                'verbose_name_plural': 'Savol formalari',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
            ],
            options={
                'verbose_name': 'Savol-javob',
                'verbose_name_plural': 'Savol-javoblar',
                'ordering': ['-created_at'],
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100, verbose_name="To'liq ism")),
                ('position', models.CharField(max_length=100, verbose_name='Lavozim')),
                ('img', models.ImageField(upload_to='images/iqtibos', verbose_name='Rasm')),
                ('body', models.TextField(max_length=500, verbose_name='Matn')),
                ('quote_choices', models.CharField(choices=[('Biz haqimizda', 'biz_haqimizda'), ('Innoweek', 'innoweek')], default='biz_haqimizda', max_length=50, verbose_name='Iqtibos turi')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
            ],
            options={
                'verbose_name': 'Iqtibos',
                'verbose_name_plural': 'Iqtiboslar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='images/team', verbose_name='Rasm')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
            ],
            options={
                'verbose_name': "Jamoa a'zosi",
                'verbose_name_plural': "Jamoa a'zolari",
                'ordering': ['-created_at'],
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='DetailServices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='texnopark.mainservices', verbose_name='Asosiy xizmat')),
            ],
            options={
                'verbose_name': 'Batafsil xizmat',
                'verbose_name_plural': 'Batafsil xizmatlar',
                'ordering': ['-created_at'],
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='ServiceSections',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sections', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='texnopark.mainservices', verbose_name='Asosiy xizmat')),
            ],
            options={
                'verbose_name': "Xizmat bo'limi",
                'verbose_name_plural': "Xizmat bo'limlari",
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='AboutCompanyTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('title', models.CharField(max_length=100, verbose_name='Sarlavha')),
                ('text', django_ckeditor_5.fields.CKEditor5Field(verbose_name='Matn')),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='texnopark.aboutcompany')),
            ],
            options={
                'verbose_name': 'Kompaniya haqida Translation',
                'db_table': 'texnopark_aboutcompany_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='DetailServicesTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('title', models.CharField(max_length=100, verbose_name='Sarlavha')),
                ('body_small', models.TextField(max_length=300, verbose_name='Qisqa matn')),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='texnopark.detailservices')),
            ],
            options={
                'verbose_name': 'Batafsil xizmat Translation',
                'db_table': 'texnopark_detailservices_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='HistoryTechnoparkTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('title', models.CharField(max_length=100, verbose_name='Sarlavha')),
                ('body_small', models.TextField(max_length=200, verbose_name='Qisqa matn')),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='texnopark.historytechnopark')),
            ],
            options={
                'verbose_name': 'Texnopark tarixi Translation',
                'db_table': 'texnopark_historytechnopark_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='MainServicesTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('title', models.CharField(max_length=100, verbose_name='Sarlavha')),
                ('body', django_ckeditor_5.fields.CKEditor5Field(verbose_name='Matn')),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='texnopark.mainservices')),
            ],
            options={
                'verbose_name': 'Asosiy xizmat Translation',
                'db_table': 'texnopark_mainservices_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='NewsTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('title', models.CharField(max_length=100, verbose_name='Sarlavha')),
                ('body_small', django_ckeditor_5.fields.CKEditor5Field(verbose_name='Matn')),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='texnopark.news')),
            ],
            options={
                'verbose_name': 'Yangilik Translation',
                'db_table': 'texnopark_news_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='QuestionsTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('question', models.CharField(max_length=100, verbose_name='Savol')),
                ('answer', models.TextField(max_length=200, verbose_name='Javob')),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='texnopark.questions')),
            ],
            options={
                'verbose_name': 'Savol-javob Translation',
                'db_table': 'texnopark_questions_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='ServiceSectionsTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('title', models.CharField(max_length=100, verbose_name='Sarlavha')),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='texnopark.servicesections')),
            ],
            options={
                'verbose_name': "Xizmat bo'limi Translation",
                'db_table': 'texnopark_servicesections_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='TeamTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('full_name', models.CharField(max_length=100, verbose_name="To'liq ism")),
                ('position', models.CharField(max_length=100, verbose_name='Lavozim')),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='texnopark.team')),
            ],
            options={
                'verbose_name': "Jamoa a'zosi Translation",
                'db_table': 'texnopark_team_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
    ]
